#!/bin/bash

#SBATCH --account=mluq
#SBATCH --time=72:00:00
#SBATCH --job-name=contFlipout
#SBATCH --mail-type=ALL
#SBATCH --mail-user=gtpash@utexas.edu
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --qos=high
#SBATCH --gres=gpu:1
#SBATCH --output=../logs/R-%x.%j.out

# Load environment.
source ~/.bashrc
conda init bash
conda activate mluq

# Navigate to working directory.
cd /projects/mluq/mluq-prop/BNN

# Run script.
srun python continuedTrainer.py --input inputs/cont.in
