#!/bin/bash

#SBATCH --account=mluq
#SBATCH --time=02:00:00
#SBATCH --job-name=Extrap
#SBATCH --mail-type=ALL
#SBATCH --mail-user=gtpash@utexas.edu
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --qos=high
#SBATCH --output=../logs/PP-%x.%j.out

# Load environment.
source ~/.bashrc
conda init bash

conda activate /projects/mluq/condaEnvs/uqprop
# conda activate mluq

# Navigate to working directory.
cd /home/gpash/S-mluq-prop/mluqprop/BNN/

# Run script.
bash run_extrap_postproc.sh
